# Generated by Django 4.2.20 on 2025-05-03 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('search_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Weather Searches',
                'ordering': ['-search_date'],
            },
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
